title: MVG's Tool Repository
description: A collection of useful tools and resources for myself and maybe others.
theme: just-the-docs

url: https://maxime-van-gendt.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
